### ISSUE TITLE
does center sampling set the label of un-chossen location to 0?

### ISSUE THREAD

**Issue by YilanWang** [yqyao/FCOS_PLUS#11]
In many text detection or other anchor-free methods，when we shrink gt to get new "center location", the original zone of gt which not be chosen is set to "ignore". But when I read this code, I find it's set to 0 (neg) directly. do I misunderstand this code or IT IS? 
many thanks for you!

**Comment by yqyao** [comment]
Yes, I try to set  the zone which not be chosen "ignore", but the result was worse than "neg". @YilanWang

**Comment by hhaAndroid** [comment]
So strange
