### ISSUE TITLE
How do you implement center sample

### ISSUE THREAD

**Issue by 18804601171** [yqyao/FCOS_PLUS#12]

**Comment by yqyao** [comment]
https://github.com/yqyao/FCOS_PLUS/blob/0d20ba34ccc316650d8c30febb2eb40cb6eaae37/maskrcnn_benchmark/modeling/rpn/fcos/loss.py#L42 @18804601171

**Comment by 18804601171** [comment]
@yqyao thank you

**Comment by 18804601171** [comment]
@yqyao What are dense points in fcos.py used for？

**Comment by yqyao** [comment]
It's my experimental code，you can ignore it @18804601171
