### ISSUE TITLE
about the benefit of center sampling in FCOS

### ISSUE THREAD

**Issue by bearcatt** [yqyao/FCOS_PLUS#3]
Why does center sampling bring so much improvement? Do you think training with center samples can lead to a better classification branch and regression branch in FCOS?

Moreover, center-ness scores of the center samples could be very close, so using center-ness during inference or not in FCOS_PLUS may lead to similar results?

**Comment by lizhe960118** [comment]
@yqyao i have the same question, why does center sampling less points but bring so much improvement?  guess who am i?hhhh

**Comment by Dwrety** [comment]
You may found intuitive explanations in key point detection. For example, in "object as points" paper, there is a key point head and the rest of the detector heads. 
I think the process in similar to context attention in common seq2seq model. The model needs guidance especially in the early stage of training. Unlike instance segmentation, even though you picked the points within a gt bbox as positive, it doesn't mean all of these points are related to that object. A common strategy is to only pick the center area of a ground truth as positive points, to avoid hard examples and gradient explosion. An area of ignore (no contribution to learning) is usually designed as well. 
You may achieve this by hard tuning a weight matrix for all the locations in the feature map. Or splat a Gaussian heat map onto a 2d space as context attention map.

**Comment by yqyao** [comment]
The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118

**Comment by tim120526** [comment]
> The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118

i agree with you. get feature from the points which far from center_point may suffer from background noises.

**Comment by yarkable** [comment]
> 
> 
> > The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118
> 
> i agree with you. get feature from the points which far from center_point may suffer from background noises.

yep, that's the problem.

**Comment by aiboys** [comment]
> > > The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118
> > 
> > 
> > i agree with you. get feature from the points which far from center_point may suffer from background noises.
> 
> yep, that's the problem.

yep, but center sampling brings positive-negative samples imbalance problem, right?

**Comment by yarkable** [comment]
> > > > The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118
> > > 
> > > 
> > > i agree with you. get feature from the points which far from center_point may suffer from background noises.
> > 
> > 
> > yep, that's the problem.
> 
> yep, but center sampling brings positive-negative samples imbalance problem, right?

Even if without center sampling, there still exists imbalance between positive-negative samples. It can be solved by other methods such as FocalLoss, rather than regarding noisy samples as positive samples.

**Comment by aiboys** [comment]
> > > > > The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118
> > > > 
> > > > 
> > > > i agree with you. get feature from the points which far from center_point may suffer from background noises.
> > > 
> > > 
> > > yep, that's the problem.
> > 
> > 
> > yep, but center sampling brings positive-negative samples imbalance problem, right?
> 
> Even if without center sampling, there still exists imbalance between positive-negative samples. It can be solved by other methods such as FocalLoss, rather than regarding noisy samples as positive samples.

是的，我赞同你的说法。所以我想表达的是，中心区域采样所带来的imbalance 与 其排除noisy points，似乎 这二者相比起来，后者带来的性能增益比前者性能减弱强，所以最终表现是模型整体性能提升

**Comment by yarkable** [comment]
> > > > > > The main idea is based on bbox labels are not very accurate, many points in bbox label may not contain objects. YOLO only use the center point leading to very few positive samples, so we try to get more accurate points using center sample. @bearcatt @lizhe960118
> > > > > 
> > > > > 
> > > > > i agree with you. get feature from the points which far from center_point may suffer from background noises.
> > > > 
> > > > 
> > > > yep, that's the problem.
> > > 
> > > 
> > > yep, but center sampling brings positive-negative samples imbalance problem, right?
> > 
> > 
> > Even if without center sampling, there still exists imbalance between positive-negative samples. It can be solved by other methods such as FocalLoss, rather than regarding noisy samples as positive samples.
> 
> 是的，我赞同你的说法。所以我想表达的是，中心区域采样所带来的imbalance 与 其排除noisy points，似乎 这二者相比起来，后者带来的性能增益比前者性能减弱强，所以最终表现是模型整体性能提升

right :D
