### ISSUE TITLE
Is the pretrained model same as "catalog://ImageNetPretrained/MSRA/R-50"?

### ISSUE THREAD

**Issue by SkeletonOne** [yqyao/FCOS_PLUS#5]

**Comment by SkeletonOne** [comment]
If so, the model weight in config file should make some change to make it a default version.

**Comment by yqyao** [comment]
The pretreained model is same as original FCOS. @SkeletonOne

**Comment by SkeletonOne** [comment]
@yqyao Yeah, thanks for your reply!
